spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/yohannes
    username: postgres
    password: 1245
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # Creates schema from your Entities at startup
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
